src/Entity/Participant.php
<?php

namespace App\Entity;

use App\Validator\ParticipantHasValidExcludes;
use App\Validator\ParticipantIsNotBlacklisted;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ParticipantHasValidExcludes(groups={"exclude_participants"})
 */
class Participant
{
    private int $id;

    private ?Party $party;

    /**
     * @Assert\NotBlank()
     */
    private string $name;

    /**
     * @Assert\NotBlank()
     *
     * @Assert\Email(
     *     mode="strict",
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     *
     * @ParticipantIsNotBlacklisted()
     */
    private string $email;

    private ?Participant $participant;

    /** @var Collection<int, Participant> */
    private Collection $excludedParticipants;

    private ?\DateTime $viewdate = null;

    private ?\DateTime $openEmailDate;

    private ?\DateTime $viewReminderSentTime;

    private string $url;

    /** @var Collection<int, WishlistItem> */
    private Collection $wishlistItems;

    private ?bool $wishlistUpdated = false;

    private ?\DateTime $updateWishlistReminderSentTime;

    private bool $partyAdmin = false;

    private ?string $ipv4;

    private ?string $ipv6;

    private ?string $geoCountry;

    private ?string $geoProvince;

    private ?string $geoCity;

    private ?\DateTime $partyStatusSentTime;

    private ?\DateTime $emptyWishlistReminderSentTime;

    private ?\DateTime $wishlistUpdatedTime;

    private bool $subscribedForUpdates = true;

    private bool $emailDidBounce = false;

    private ?\DateTime $invitationSentDate;

    private bool $isHashed = false;

    public function __construct()
    {
        $this->url = base_convert(sha1(uniqid((string) mt_rand(), true)), 16, 36);
        $this->excludedParticipants = new ArrayCollection();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getParty(): ?Party
    {
        return $this->party;
    }

    public function setParty(?Party $party): Participant
    {
        $this->party = $party;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): Participant
    {
        $this->name = preg_replace('/[^[:alnum:][:space:][\-_]]/u', '', $name);

        return $this;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): Participant
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @deprecated use getAssignedParticipant()
     */
    public function getParticipant(): Participant
    {
        return $this->participant;
    }

    public function getAssignedParticipant(): ?Participant
    {
        return $this->participant;
    }

    public function setAssignedParticipant(?Participant $participant): Participant
    {
        $this->participant = $participant;

        return $this;
    }

    public function getViewdate(): ?\DateTime
    {
        return $this->viewdate;
    }

    public function setViewdate(?\DateTime $viewdate): Participant
    {
        $this->viewdate = $viewdate;

        return $this;
    }

    public function getUrl(): string
    {
        return $this->url;
    }

    public function setUrl(string $url): Participant
    {
        $this->url = $url;

        return $this;
    }

    public function getWishlistUpdated(): ?bool
    {
        return $this->wishlistUpdated;
    }

    public function setWishlistUpdated(?bool $wishlistUpdated): Participant
    {
        $this->wishlistUpdated = $wishlistUpdated;

        return $this;
    }

    public function getUpdateWishlistReminderSentTime(): ?\DateTime
    {
        return $this->updateWishlistReminderSentTime;
    }

    public function setUpdateWishlistReminderSentTime(?\DateTime $updateWishlistReminderSentTime): void
    {
        $this->updateWishlistReminderSentTime = $updateWishlistReminderSentTime;
    }

    public function getViewReminderSentTime(): ?\DateTime
    {
        return $this->viewReminderSentTime;
    }

    public function setViewReminderSentTime(?\DateTime $viewReminderSentTime): void
    {
        $this->viewReminderSentTime = $viewReminderSentTime;
    }

    public function getWishlistItems(): Collection
    {
        return $this->wishlistItems;
    }

    /**
     * @param Collection<int, WishlistItem> $wishlistItems
     */
    public function setWishlistItems($wishlistItems): void
    {
        $this->wishlistItems = $wishlistItems;
    }

    public function addExcludedParticipant(Participant $excludedParticipant): Participant
    {
        $this->excludedParticipants->add($excludedParticipant);

        return $this;
    }

    public function removeExcludedParticipant(Participant $excludedParticipant): void
    {
        $this->excludedParticipants->removeElement($excludedParticipant);
    }

    public function getExcludedParticipants(): ArrayCollection|Collection
    {
        return $this->excludedParticipants;
    }

    public function isPartyAdmin(): bool
    {
        return $this->partyAdmin;
    }

    public function setPartyAdmin(bool $partyAdmin): void
    {
        $this->partyAdmin = $partyAdmin;
    }

    public function getIp(): ?string
    {
        if (null !== $this->getIpv4()) {
            return $this->getIpv4();
        }

        return $this->getIpv6();
    }

    public function setIp(?string $ip): void
    {
        if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
            $this->setIpv4($ip);
        } elseif (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
            $this->setIpv6($ip);
        }
    }

    private function getIpv4(): ?string
    {
        return $this->ipv4;
    }

    private function setIpv4(?string $ipv4): Participant
    {
        $this->ipv4 = $ipv4;

        return $this;
    }

    private function getIpv6(): ?string
    {
        return $this->ipv6;
    }

    private function setIpv6(?string $ipv6): Participant
    {
        $this->ipv6 = $ipv6;

        return $this;
    }

    public function getGeoCountry(): ?string
    {
        return $this->geoCountry;
    }

    public function setGeoCountry(?string $geoCountry): Participant
    {
        $this->geoCountry = $geoCountry;

        return $this;
    }

    public function getGeoProvince(): ?string
    {
        return $this->geoProvince;
    }

    public function setGeoProvince(?string $geoProvince): Participant
    {
        $this->geoProvince = $geoProvince;

        return $this;
    }

    public function getGeoCity(): ?string
    {
        return $this->geoCity;
    }

    public function setGeoCity(?string $geoCity): Participant
    {
        $this->geoCity = $geoCity;

        return $this;
    }

    public function getPartyStatusSentTime(): \DateTime
    {
        return $this->partyStatusSentTime;
    }

    public function setPartyStatusSentTime(\DateTime $partyStatusSentTime): void
    {
        $this->partyStatusSentTime = $partyStatusSentTime;
    }

    public function getEmptyWishlistReminderSentTime(): ?\DateTime
    {
        return $this->emptyWishlistReminderSentTime;
    }

    public function setEmptyWishlistReminderSentTime(?\DateTime $emptyWishlistReminderSentTime): void
    {
        $this->emptyWishlistReminderSentTime = $emptyWishlistReminderSentTime;
    }

    public function getWishlistUpdatedTime(): ?\DateTime
    {
        return $this->wishlistUpdatedTime;
    }

    public function setWishlistUpdatedTime(?\DateTime $wishlistUpdatedTime): void
    {
        $this->wishlistUpdatedTime = $wishlistUpdatedTime;
    }

    public function unsubscribe(): void
    {
        $this->subscribedForUpdates = false;
    }

    public function subscribe(): void
    {
        $this->subscribedForUpdates = true;
    }

    public function isSubscribed(): bool
    {
        return $this->subscribedForUpdates;
    }

    public function getOpenEmailDate(): ?\DateTime
    {
        return $this->openEmailDate;
    }

    public function setOpenEmailDate(?\DateTime $openEmailDate): void
    {
        $this->openEmailDate = $openEmailDate;
    }

    public function getEmailDidBounce(): bool
    {
        return $this->emailDidBounce;
    }

    public function setEmailDidBounce(mixed $emailDidBounce): void
    {
        $this->emailDidBounce = $emailDidBounce;
    }

    public function getInvitationSentDate(): ?\DateTime
    {
        return $this->invitationSentDate;
    }

    public function setInvitationSentDate(?\DateTime $invitationSentDate): void
    {
        $this->invitationSentDate = $invitationSentDate;
    }

    public function isHashed(): bool
    {
        return $this->isHashed;
    }

    public function setIsHashed(bool $isHashed): void
    {
        $this->isHashed = $isHashed;
    }
}

src/Controller/Api/Participant/JoinController.php
<?php

declare(strict_types=1);

namespace App\Controller\Api\Participant;

use App\Entity\Party;
use App\Model\Exception\InvalidJoinLink;
use App\Model\JoinLinkDetails;
use App\Repository\PartyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

final class JoinController extends AbstractController
{
    public function __construct(
        private NormalizerInterface $normalizer
    ) {}

    /**
     * @Route("/api/join/{joinUrl}", name="get_info_for_participants")
     */
    public function getInfoForParticipants(string $joinUrl, PartyRepository $partyRepository): Response
    {
        try {
            $details = $partyRepository->getDetailsForJoinUrl($joinUrl);

            return new JsonResponse(
                $this->normalizer->normalize($details)
            );
        } catch (InvalidJoinLink) {
            return new JsonResponse(
                [
                'statusCode' => 'NOT_FOUND',
                'statusText' => 'Party not found',
                ],
                404
            );
        }
    }
}

src/Controller/Participant/DumpParticipantsController.php
<?php

declare(strict_types=1);

namespace App\Controller\Participant;

use App\Repository\ParticipantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class DumpParticipantsController extends AbstractController
{
    #[Route('/{_locale}/dump-participants', name: 'dump_participants', methods: ['GET'])]
    public function dumpAction(ParticipantRepository $repository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADWORDS');

        $startCrawling = new \DateTime();
        $startCrawling->sub(new \DateInterval('P4M'));

        return $this->render('Participant/dumpParticipants.html.twig', [
            'participants' => $repository->findAfter($startCrawling),
        ]);
    }
}

src/Controller/Participant/ExposeParticipantsController.php
<?php

declare(strict_types=1);

namespace App\Controller\Participant;

use App\Entity\Party;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class ExposeParticipantsController extends AbstractController
{
    #[Route('/{_locale}/participants/expose/{listurl}', name: 'expose_participants', methods: ['GET'])]
    public function indexAction(Party $party): Response
    {
        return $this->render('Participant/exposeAll.html.twig', [
            'party' => $party,
        ]);
    }
}

src/Controller/Participant/JoinController.php
<?php

declare(strict_types=1);

namespace App\Controller\Participant;

use App\Entity\Participant;
use App\Entity\Party;
use App\Form\Type\AddParticipantType;
use App\Repository\PartyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class JoinController extends AbstractController
{
    #[Route('/{_locale}/join/{joinurl}', name: 'join_party')]
    public function joinAction(Request $request, string $joinurl, PartyRepository $partyRepository, EntityManagerInterface $em): RedirectResponse|Response
    {
        $addParticipantForm = null;
        /** @var ?Party $party */
        $party = $partyRepository->findOneBy(['joinurl' => $joinurl, 'joinmode' => 1, 'created' => 0]);

        if (null !== $party) {
            $addParticipantForm = $this->createForm(AddParticipantType::class, new Participant(), [
                'action' => $this->generateUrl('join_party', ['joinurl' => $party->getJoinurl()]),
            ]);
            $addParticipantForm->handleRequest($request);

            if ($addParticipantForm->isSubmitted() && $addParticipantForm->isValid()) {
                /** @var Participant $newParticipant */
                $newParticipant = $addParticipantForm->getData();
                $newParticipant->setParty($party);
                $em->persist($newParticipant);
                $em->flush();

                return $this->redirectToRoute('join_party_joined', ['joinurl' => $party->getJoinurl()]);
            }
        }

        return $this->render('Participant/show/join.html.twig', [
            'party' => $party,
            'form' => isset($addParticipantForm) ? $addParticipantForm->createView() : null,
        ]);
    }

    #[Route('/{_locale}/joined/{joinurl}', name: 'join_party_joined')]
    public function joinedAction(string $joinurl, PartyRepository $partyRepository): Response
    {
        /** @var Party $party */
        $party = $partyRepository->findOneBy(['joinurl' => $joinurl, 'joinmode' => 1, 'created' => 0]);

        return $this->render('Participant/show/join.html.twig', [
            'party' => $party,
            'form' => null,
        ]);
    }
}

src/Controller/Participant/ResendParticipantController.php
<?php

declare(strict_types=1);

namespace App\Controller\Participant;

use App\Entity\Participant;
use App\Mailer\MailerService;
use App\Service\UnsubscribeService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class ResendParticipantController extends AbstractController
{
    private $unsubscribeService;

    private $translator;

    private $mailerService;

    public function __construct(
        UnsubscribeService $unsubscribeService,
        TranslatorInterface $translator,
        MailerService $mailerService,
    ) {
        $this->unsubscribeService = $unsubscribeService;
        $this->translator = $translator;
        $this->mailerService = $mailerService;
    }

    #[Route('/{_locale}/resend/{listurl}/{url}', name: 'resend_participant', methods: ['GET'])]
    public function resendAction($listurl, Participant $participant): RedirectResponse
    {
        if ($participant->getParty()->getListurl() !== $listurl) {
            throw $this->createNotFoundException();
        }

        if ($this->unsubscribeService->isBlacklisted($participant)) {
            $this->addFlash('danger', $this->translator->trans('flashes.resend_participant.blacklisted'));
        } else {
            $this->mailerService->sendSecretSantaMailForParticipant($participant);

            $name = htmlspecialchars($participant->getName(), ENT_QUOTES);
            $this->addFlash('success', $this->translator->trans('flashes.resend_participant.resent', ['%email%' => $name]));
        }

        return $this->redirectToRoute('party_manage', ['listurl' => $listurl]);
    }
}

src/Controller/Participant/ShowController.php
<?php

declare(strict_types=1);

namespace App\Controller\Participant;

use App\Entity\Participant;
use App\Form\Type\AnonymousMessageFormType;
use App\Form\Type\WishlistType;
use App\Service\ParticipantService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

class ShowController extends AbstractController
{
    #[Route('/{_locale}/participant/{url}', name: 'participant_view', methods: ['GET'])]
    public function showAction(Request $request, Participant $participant, ParticipantService $participantService)
    {
        if ($participant->getParty()->getEventdate() < new \DateTime('-2 years')) {
            return $this->render('Participant/show/expired.html.twig', [
                'participant' => $participant,
            ]);
        }

        $wishlistForm = $this->createForm(WishlistType::class, $participant, [
            'action' => $this->generateUrl('wishlist_update', ['url' => $participant->getUrl()]),
        ]);
        $messageForm = $this->createForm(AnonymousMessageFormType::class, null, [
            'action' => $this->generateUrl('participant_communication_send_message'),
        ]);

        $participantService->logFirstAccess($participant, $request->getClientIp());

        return $this->render('Participant/show/valid.html.twig', [
            'participant' => $participant,
            'wishlistForm' => $wishlistForm->createView(),
            'messageForm' => $messageForm->createView(),
        ]);
    }
}

templates/Participant/show/base.html.twig
{% extends "base.html.twig" %}
{% block metadata %}
    {{ parent() }}
    <meta name="robots" content="noindex, nofollow">
{% endblock %}

templates/Participant/show/expired.html.twig
{% extends "Participant/show/base.html.twig" %}

{% block metadata %}
    {{ parent() }}
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9463520136816719" crossorigin="anonymous"></script>
{% endblock %}

{% block main %}
    <div class="alert alert-danger" role="alert">
        {{ 'participant_show_expired.message.expired' | trans | raw }}
    </div>

    {% if participant.geoCountry in ["BE", "NL"] %}
        <div class="row text-center">
            <div class="col mb-2">
                <a href="https://kersthits.lnk.to/playlist" rel="noopener noreferrer" target="_blank">
                    <img src="{{ absolute_url(asset('/sony2021.jpg')) }}" width="100%">
                </a>
            </div>
        </div>
    {% endif %}

    <div class="box">
        <div class="row text-center">
            <div class="span4 visible-xs-inline-block">
                <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9463520136816719"
                        crossorigin="anonymous"></script>
                <!-- Horizontal banner -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-9463520136816719"
                     data-ad-slot="7244544166"
                     data-ad-format="auto"
                     data-full-width-responsive="true"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
        </div>
    </div>
{% endblock %}

templates/Participant/show/valid.html.twig
{% extends "Participant/show/base.html.twig" %}

{% block metadata %}
    {{ parent() }}
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9463520136816719" crossorigin="anonymous"></script>
{% endblock %}

{% block main %}
    <div class="box">
        <div class="row participant-title-row">
            <div class="col-xs-12 col-sm-5 col-md-5">
                <h1>{{ 'participant_show_valid.participant.title'|trans }}</h1>

                {{ 'participant_show_valid.participant.body'|trans({'%name%': participant.name|escape})|raw }}

                <div class="yoursecretsant" data-hj-masked>
                    <span class="yourgift">{{ participant.assignedParticipant.name }}</span>
                </div>
            </div>
            <div class="col-sm-7 col-md-5 ml-auto hidden-xs">
                <div class="party-info">
                    <h2>{{ 'participant_show_base.headers.title'|trans|raw }}</h2>
                    <div id="partyDetails">
                        <ul class="liststyle1">
                            <li><strong>{{ 'participant_show_base.headers.date'|trans }}: </strong> {{ participant.party.eventdate|format_datetime('medium', 'none') }}</li>
                            <li><strong>{{ 'participant_show_base.headers.location'|trans }}: </strong> {{ participant.party.location }}</li>
                            <li><strong>{{ 'participant_show_base.headers.amount'|trans }}: </strong> {{ participant.party.amount }}</li>
                            <li><strong>{{ 'participant_show_base.headers.num_people'|trans }}: </strong> {{ participant.party.participants|length }}</li>
                            <li><strong>{{ 'participant_show_base.headers.person_created_list'|trans }}: </strong> <span data-hj-masked>{{ participant.party.participants|first.name }} ({{ participant.party.participants|first.email }})</span>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="my-secretsanta">
            <div class="card mb-4">
                <div class="card-body">
                    <h4 data-hj-masked>{{ 'participant_show_valid.participant.wishlist_from'|trans({'%name%': participant.assignedParticipant.name}) }}</h4>
                    {% if participant.assignedParticipant.wishlistitems|length == 0 %}
                        {{ 'participant_show_valid.participant.wishlist_not_provided'|trans({'%name%': participant.assignedParticipant.name}) }}.
                        {% if participant.assignedParticipant.isSubscribed == true %}
                            {{ 'participant_show_valid.participant.message_for_wishlist'|trans|raw }}
                        {% endif %}
                    {% else %}
                        <ul class="wishlist">
                            {% for item in participant.assignedParticipant.wishlistitems %}
                                <li class="wishlistitem">{{ item.description|escape|linkify|raw }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    {% if participant.geoCountry in ['BE', 'NL'] %}
                        {# Show local links #}
                        <br><br>
                        <a href="https://partner.bol.com/click/click?p=1&t=url&s=50354&f=TXL&url=https%3A%2F%2Fwww.bol.com%2F{{ participant.geoCountry|lower }}%2Fnl%2Fsf%2Fcadeauwinkel-volwassenen%2F"
                           target="_blank" rel="noopener noreferrer">
                            {{ 'participant_show_valid.participant.find_gift'|trans }}
                        </a><br>
                    {% else %}
                        {# Show global Amazon link #}
                        {#
                        Currently disabled due to no valid partner account
                        <br><br>
                        <a href="https://amzn.to/48YJb0v"
                           target="_blank" rel="noopener noreferrer">
                           {{ 'participant_show_valid.participant.find_gift'|trans }}
                        </a><br>
                        #}
                    {% endif %}
                </div>
            </div>
            {% if participant.assignedParticipant.isSubscribed == true %}
                <div class="panel panel-default bottom-spacer" id="messagePanel">
                    <button class="js-secret-message-toggle btn btn-light mb-3" type="button" data-toggle="collapse" data-target="#collapsedMessage">
                        {{ 'participant_show_valid.anonymous_message.title'|trans({'%name%': participant.assignedParticipant.name}) }} ↓
                    </button>
                    <div id="collapsedMessage" class="card collapse">
                        <div class="card-body">
                            <div class="alert alert-warning" role="alert" id="anonwarning">
                                <i class="fa fa-exclamation-triangle"></i> {{ 'participant_show_valid.anonymous_message.warning_anonymous' | trans }}
                            </div>
                            {{ form_start(messageForm) }}
                            <div class="form-group">

                                {{ form_label(messageForm.message) }}
                                {{ form_widget(messageForm.message, {'attr': {'class': 'form-control'}}) }}
                                {% for error in messageForm.message.vars.errors %}
                                    <strong>{{ error.message }}</strong><br>
                                {% endfor %}
                            </div>
                            {{ form_widget(messageForm.participant, {'value': participant.url}) }}
                            <button id="btn_send_anon_message"
                                    type="submit"
                                    class="btn btn-primary">{{ 'participant_show_valid.anonymous_message.send_button' |trans }}</button>
                            {{ form_end(messageForm) }}
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>

        {% if participant.geoCountry in ["BE", "NL"] %}
            <div class="row text-center">
                <div class="col mb-2">
                    <a href="https://kersthits.lnk.to/playlist" rel="noopener noreferrer" target="_blank">
                        <img src="{{ absolute_url(asset('/sony2021.jpg')) }}" width="100%">
                    </a>
                </div>
            </div>
        {% endif %}

        <div class="row text-center">
            <div class="col mb-2">
                <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9463520136816719"
                        crossorigin="anonymous"></script>
                <!-- Horizontal banner -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-9463520136816719"
                     data-ad-slot="7244544166"
                     data-ad-format="auto"
                     data-full-width-responsive="true"></ins>
                <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
        </div>

        <h1>{{ 'participant_show_valid.wishlist.title'|trans }}</h1>

        <div class="description">{{ 'participant_show_valid.wishlist.description'|trans|raw }}</div>

        <div class="box ajax-response mt-4">
            <div class="alert alert-warning empty" style="display:none;">
                <div>{{ 'participant_show_valid.flashes.wishlist.empty_row'|trans|raw }}</div>
            </div>
            <div class="alert alert-success added" style="display:none;">
                <div>{{ 'participant_show_valid.flashes.wishlist.added'|trans|raw }}</div>
            </div>
            <div class="alert alert-success updated" style="display:none;">
                <div>{{ 'participant_show_valid.flashes.wishlist.updated'|trans|raw }}</div>
            </div>
            <div class="alert alert-success removed" style="display:none;">
                <div>{{ 'participant_show_valid.flashes.wishlist.removed'|trans|raw }}</div>
            </div>
        </div>

        {{ form_start(wishlistForm, {'attr': {'id': 'add_item_to_wishlist_form'}}) }}

        <table class="wishlist-items table table-striped">
            <thead>
            <tr>
                <th class="participant-number-header">#</th>
                <th>{{ 'participant_show_valid.label.description'|trans }}</th>
                <th style="text-align: right;">
                    <button type="button" class="btn btn-mini btn-success add-new-participant" id="wishlist-add-item">
                        <i class="fa fa-plus-circle"></i> <span
                                class="text_remove_wishlist">{{ 'participant_show_valid.btn.add_wishlist'|trans }}</span>
                    </button>
                </th>
            </tr>
            </thead>
            <tbody data-prototype="{% apply escape %}{% include 'Helpers/prototypeWishlist.html.twig' with {'item': wishlistForm.wishlistItems.vars['prototype']} %}{% endapply %}">
            {% if wishlistForm.wishlistItems |length == 0 %}
                <tr class="noitems">
                    <td colspan="3">{{ 'participant_show_valid.wishlist.empty'|trans }}</td>
                </tr>
            {% else %}
                {% for item in wishlistForm.wishlistItems %}
                    <tr class="wishlistitem">
                        <td {% if form_errors(item.rank) %}class="error"{% endif %}>{{ form_widget(item.rank) }}<span
                                    class="rank">{{ item.rank.vars.value }}</span></td>
                        <td {% if form_errors(item.description) %}class="error"{% endif %}>{{ form_widget(item.description, {'attr': {'class': 'form-control wishlistitem-description'} }) }}</td>
                        <td style="text-align: right;">
                            <button type="submit" class="btn btn-mini btn-success update-participant" style="display: none">
                                <i class="fa fa-check-circle"></i> <span
                                        class="text_remove_wishlist">{{ 'participant_show_valid.btn.update_item'|trans }}</span>
                            </button>
                            <button type="button" class="btn btn-mini btn-danger remove-participant">
                                <i class="fa fa-times-circle"></i> <span
                                        class="text_remove_wishlist">{{ 'participant_show_valid.btn.remove_item'|trans }}</span>
                            </button>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
            </tbody>
        </table>

        {{ form_end(wishlistForm, {'render_rest': false}) }}

    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('build/js/wishlist.js') }}"></script>
    {{ form_javascript(wishlistForm) }}
{% endblock %}